export const elSalvadorCode:any = {
    SLV1343: {
        name: 'Ahuachapan',
        municipalities: {
            'SLV1343SANFRANCISCOMELENDEZ': 'San Francisco Menendez',
            'SLV1343TACUBA': 'Tacuba',
            'SLV1343TURIN': 'Turin',
            'SLV1343ELREFUGIO': 'El Refugio',
            'SLV1343ATIQUIZAYA': 'Atiquizaya',
            'SLV1343SANLORENZO': 'San Lorenzo',
            'SLV1343AHUACHAPAN':'Ahuachapan',
            'SLV1343APANECA':'Apaneca',
            'SLV1343CONCEPCIONDEATACO': 'Concepcion de Ataco',
            'SLV1343SANPEDROPUXTLA': 'San Pedro Puxtla',
            'SLV1343GUAYMANGO': 'Guaymango',
            'SLV1343JUJUTLA': 'Jujutla'
        }
    },
    SLV1344: {
        name: 'Cabanas',
        municipalities: {
            'SLV1344GUACOTECTI': 'Guacotecti',
            'SLV1344SANISIDRO': 'San Isidro',
            'SLV1344DOLORES': 'Dolores',
            'SLV1344VICTORIA': 'Victoria',
            'SLV1344JUTIAPA': 'Jutiapa',
            'SLV1344TEJUTEPEQUE': 'Tejutepeque',
            'SLV1344CINQUERA': 'Cinquera',
            'SLV1344SENSUNTEPEQUE': 'Sensuntepeque',
            'SLV1344ILOBASCO': 'Ilobasco'
        }
    },
    SLV1345: {
        name: 'Cuscatlan',
        municipalities: {
            'SLVCUSSANTACRUZANALQUITO': 'Santa Cruz Analquito',
            'SLVCUSCANDELARIA': 'Candelaria',
            'SLVCUSSANRAMON': 'San Ramon',
            'SLVCUSSANTACRUZMICHAPA': 'Santa Cruz Michapa',
            'SLVCUSSANCRISTOBAL': 'San Cristobal',
            'SLVCUSCOJUTEPEQUE': 'Cojutepeque',
            'SLVCUSELCARMEN': 'El Carmen',
            'SLVCUSSANRAFAELCEDROS': 'San Rafael Cedros',
            'SLVCUSELROSARIO': 'El Rosario',
            'SLVCUSMONTESANJUAN': 'Montes San Juan',
            'SLVCUSTENANCINGO': 'Tenancingo',
            'SLVCUSSANPEDROPERULAPAN': 'San Pedro Perulapan',
            'SLVCUSSANBARTOLOMENPERULAPIA': 'San Bartolomen Perulapia',
            'SLVCUSORATORIODECONCEPCION': 'Oratorio de Concepcion',
            'SLVCUSSANJOSEGUAYABAL': 'San Jose Guayabal',
            'SLVCUSSUCHITOTO': 'Suchitoto'
        }
    },
    SLV1346: {
        name: 'La Libertad',
        municipalities: {
            'SLV1346JICALAPA': 'Jicalapa',
            'SLV1346TEOTEPEQUE': 'Teotepeque',
            'SLV1346TEPECOYO': 'Tepecoyo',
            'SLV1346SACACOYO': 'Sacacoyo',
            'SLV1346CIUDADARCE': 'Ciudad Arce',
            'SLV1346SANPABLOTACACHICO': 'San Pablo Tacachico',
            'SLV1346SANJUANOPICO': 'San Juan Opico',
            'SLV1346SANMATIAS': 'San Matias',
            'SLV1346QUEZALTEPEQUE': 'Quezaltepeque',
            'SLV1346JAYAQUE': 'Jayaque',
            'SLV1346COLON': 'Colon',
            'SLV1346TALNIQUE': 'Talnique',
            'SLV1346CHILTIUPAN': 'Chiltiupan',
            'SLV1346TAMANIQUE': 'Tamanique',
            'SLV1346SANTATECLA': 'Santa Tecla',
            'SLV1346COMASAGUA': 'Comasagua',
            'SLV1346NUEVOCUSCATLAN': 'Nuevo Cuscatlan',
            'SLV1346ZARAGOZA': 'Zaragoza',
            'SLV1346ANTIGUOCUSCATLAN': 'Antiguo Cuscatlan',
            'SLV1346HUIZUCAR': 'Huizucar',
            'SLV1346SANJOSEVILLANUEVA': 'San Jose Villanueva',
            'SLV1346LALIBERTAD': 'La Libertad'
        }
    },
    SLV1347: {
        name: 'La Paz',
        municipalities: {
            'SLVLPASANLUISTALPA': 'San Luis Talpa',
            'SLVLPAOLOCUILTA': 'Olocuilta',
            'SLVLPASANJUANTALPA': 'San Juan Talpa',
            'SLVLPACUYULTITAN': 'Cuyultitan',
            'SLVLPATAPALHUACA': 'Apalhuaca',
            'SLVLPASANFRANCISCOCHINAMECA': 'San Francisco Chinameca',
            'SLVLPASANMIGUELTEPEZONTES': 'San Miguel Tepezontes',
            'SLVLPASANEMIGDIO': 'San Emigdio',
            'SLVLPAPARAISODEOSORIO': 'Paraiso de Osorio',
            'SLVLPAJERUSALEN': 'Jerusalen',
            'SLVLPAMERCEDESLACEIBA': 'Mercedes la Ceiba',
            'SLVLPASANTAMARIAOSTUMA': 'Santa Maria Ostuma',
            'SLVLPASANJUANTEPEZONTES': 'San Juan Tepezontes',
            'SLVLPASANPEDRONONUALCO': 'San Pedro Nonualco',
            'SLVLPASANANTONIOMASAHUAT': 'San Antonio Masahuat',
            'SLVLPASANPEDROMASAHUAT': 'San Pedro Masahuat',
            'SLVLPAELROSARIO': 'El Rosario',
            'SLVLPASANTIAGONONUALCO': 'Santiago Nonualco',
            'SLVLPASANRAFAELOBRAJUELO': 'San Rafael Obrajuelo',
            'SLVLPASANJUANNONUALCO': 'San Juan Nonualco',
            'SLVLPAZACATECOLUCA': 'Zacatecoluca',
            'SLVLPASANLUISLAHERRADURA': 'San Luis la Herradura'
        }
    },
    SLV1348: {
        name: 'Sonsonate',
        municipalities: {
            'SLVSONACAJUTLA': 'Acajutla',
            'SLVSONSANTODOMINDODEGUZMAN': 'Santo Domingo de Guzman',
            'SLVSONSANTACATARINAMASHUAT': 'Santa Catarina Masahuat',
            'SLVSONSALCOATITAN': 'Salcoatitan',
            'SLVSONJUAYUA': 'Juayua',
            'SLVSONNAHUIZALCO': 'Nahuizalco',
            'SLVSONSANANTONIODELMONTE': 'San Antonio del Monte',
            'SLVSONSONZACATE': 'Sonzacate',
            'SLVSONNAHUILINGO': 'Nahuilingo',
            'SLVSONSONSONATE': 'Sonsonate',
            'SLVSONCALUCO': 'Caluco',
            'SLVSONCUISNAHUAT': 'Cuisnahuat',
            'SLVSONSANTAISABELISHUATAN': 'Santa Isabel Ishuatan',
            'SLVSONSANJULIAN': 'San Julian',
            'SLVSONARMENIA': 'Armenia',
            'SLVSONIZALCO': 'Izalco'
        }
    },
    SLV1349: {
        name: 'San Salvador',
        municipalities: {
            'SLVSSAROSARIODEMORA': 'Rosario de Mora',
            'SLVSSAPANCHIMALCO': 'Panchimalco',
            'SLVSSASANTOTOMAS': 'Santo Tomas',
            'SLVSSASANMARCOS': 'San Marcos',
            'SLVSSALAGODEILOPANGO': 'Lago de Ilopango',
            'SLVSSASANMARCOS-2': 'San Marcos',
            'SLVSSAILOPANGO': 'Ilopango',
            'SLVSSASOYAPANGO': 'Soyapango',
            'SLVSSASANSALVADOR': 'San Salvador',
            'SLVSSASANMARTIN': 'San Martin',
            'SLVSSATONACATEPEQUE': 'Tonacatepeque',
            'SLVSSACIUDADDELGADO': 'Ciudad Delgado',
            'SLVSSACUSCATANCINGO': 'Cuscatancingo',
            'SLVSSAAYUTUXTEPEQUE': 'Ayutuxtepeque',
            'SLVSSAMEJICANO': 'Mejicano',
            'SLVSSAAPOPA': 'Apopa',
            'SLVSSANEJAPA': 'Nejapa',
            'SLVSSAGUAZAPA': 'Guazapa',
            'SLVSSAAGUILARES': 'Aguilares',
            'SLVSSAELPAISNAL': 'El Paisnal'
        }
    },
    SLV1350: {
        name: 'La Union',
        municipalities: {
            'SLVLUNINTIPUCA': 'Intipuca',
            'SLVLUNLISLIQUE': 'Lislique',
            'SLVLUNNUEVAESPARTA': 'Nueva Esparta',
            'SLVLUNPOLOROS': 'Poloros',
            'SLVLUNCONCEPCIONDEORIENTE': 'Concepcion de Oriente',
            'SLVLUNANAMOROS': 'Anamoros',
            'SLVLUNELSAUCE': 'El Sauce',
            'SLVLUNSANTAROSADELIMA': 'Santa Rosa de Lima',
            'SLVLUNSANJOSE': 'San Jose',
            'SLVLUNBOLIVAR': 'Bolivar',
            'SLVLUNYUCUAIQUIN': 'YuCuaiquin',
            'SLVLUNYAYANTIQUE': 'Yayantique',
            'SLVLUNSANALEJO': 'San Alejo',
            'SLVLUNELCARMEN': 'El Carmen',
            'SLVLUNLAUNION': 'La Union',
            'SLVLUNCONCHAGUA': 'Conchagua',
            'SLVLUNPASAQUINA': 'Pasaquina',
        }
    },
    SLV1351: {
        name: 'Morazan',
        municipalities: {
            'SLVMORELDIVISADERO': 'Reldivisadero',
            'SLVMORJOCORO': 'Jocoro',
            'SLVMORSOCIEDAD': 'Sociedad',
            'SLVMORSANCARLOS': 'San Carlos',
            'SLVMORSANFRANCISCOGOTERA': 'San Francisco Gotera',
            'SLVMORYAMABAL': 'Yamabal',
            'SLVMORGUATALIAGUA': 'Guataliagua',
            'SLVMORSENSEMBRA': 'Sensembra',
            'SLVMORSANSIMON': 'San Simon',
            'SLVMORCHILANGA': 'Chilanga',
            'SLVMORJOLOOAIQUINN': 'Joloaquin',
            'SLVMORSANISIDRO': 'San Isidro',
            'SLVMORGUALOCOCTI': 'Gualococti',
            'SLVMORDELICIASDECONCEPCION': 'Delicia de Concepcion',
            'SLVMOROSICALA': 'Osicala',
            'SLVMORLOLOTIQUILLO': 'Lolotiquillo',
            'SLVMORCORINTIO': 'Corintio',
            'SLVMORCACAOPERA': 'Cacaopera',
            'SLVMORTOROLA': 'Torola',
            'SLVMORSANFERNANDO': 'San Fernando',
            'SLVMORELROSARIO': 'El Rosario',
            'SLVMORMEANGUERA': 'Meanguera',
            'SLVMORJOCOATIQUE': 'Jocoatiuqe',
            'SLVMORJOATECA': 'Joateca',
            'SLVMORARAMBALA': 'Arambala',
            'SLVMORPERQUIN': 'Perquin',
        }
    },
    SLV1352: {
        name: 'San Miguel',
        municipalities: {
            'SLVSMISANANTONIO': 'San Antonio',
            'SLVSMISANGERARDO': 'San Gerardo',
            'SLVSMICAROLINA': 'Carolina',
            'SLVSMISANLUISDELAREINA': 'San Luis de la Reina',
            'SLVSMINUEVOEDENDESANJUAN': 'Nuevo Eden de San Juan',
            'SLVSMICIUDADBARRIOS': 'Ciudad barrios',
            'SLVSMISESORI': 'Sesori',
            'SLVSMILOLOTIQUE': 'Lolotique',
            'SLVSMICHAPELTIQUE': 'Chapeltique',
            'SLVSMICHINAMECA': 'Chinameca',
            'SLVSMINUEVAGUADALUPE': 'Nueva Guadalupe',
            'SLVSMIMONCAGUA': 'Moncagua',
            'SLVSMIQUELAPA': 'Quelapa',
            'SLVSMISANJORGE': 'San Jorge',
            'SLVSMICOMACARAN': 'Comacaran',
            'SLVSMIULUAZAPA': 'Uluazapa',
            'SLVSMISANRAFAELORIENTE': 'San Rafael oriente',
            'SLVSMIELTRANSITO': 'El Transito',
            'SLVSMICHIRILAGUA': 'Chirilagua',
            'SLVSMISANMIGUEL': 'San Miguel'
        }
    },
    SLV1353: {
        name: 'San Vicente',
        municipalities: {
            'SLVSVISANSEBASTIAN': 'San Sebastian',
            'SLVSVISANTODOMINGO': 'Santo Domingo',
            'SLVSVISANLORENZO': 'San Lorenzo',
            'SLVSVISANESTEBANCATARINA': 'San Esteban Catarina',
            'SLVSVIVERAPAZ': 'Verapaz',
            'SLVSVIGUADALUPE': 'Guadalupe',
            'SLVSVITEPETITAN': 'Tepetitan',
            'SLVSVISANCAYETANOISTEPEQUE': 'San Cayetano Istepeque',
            'SLVSVISANTACLARA': 'Santa Clara',
            'SLVSVIAPASTEPEQUE': 'Apastepeque',
            'SLVSVISANILDEFONSO': 'San Ildefonso',
            'SLVSVISANVICENTE': 'San Vicente',
            'SLVSVITECOLUCA': 'Tecoluca',
        }
    },
    SLV1354: {
        name: 'Usulutan',
        municipalities: {
            'SLVUSUNUEVAGRANADA': 'Nueva Granada',
            'SLVUSUESTANZUELA': 'Estanzuela',
            'SLVUSUELTRIUNFU': 'EL Triunfo',
            'SLVUSUSANBUANAVENTURA': 'San Buenaventura',
            'SLVUSUMERCEDESUMANA': 'Mercedes Umana',
            'SLVUSUJUCUAPAN': 'Jucuapan',
            'SLVUSUALEGRIA': 'Alegria',
            'SLVUSUSANTIAGODEMARIA': 'Santiago de Maria',
            'SLVUSUBERLIN': 'Berlin',
            'SLVUSUSANTAELENA': 'Santa Elena',
            'SLVUSUEREGUAYQUIN': 'Ereguayquin',
            'SLVUSUCALIFORNIA': 'California',
            'SLVUSUTECAPAN': 'Tecapan',
            'SLVUSUOZATLAN': 'Souzatlan',
            'SLVUSUSANFRANCISCOJAVIER': 'San Francisco Javier',
            'SLVUSUSANAGUSTIN': 'San Agustin',
            'SLVUSUJIQUILISCO': 'Jiquilisco',
            'SLVUSUSANTAMARIA': 'Santa Maria',
            'SLVUSUCONCEPCIONBARES': 'Concepcion Batres',
            'SLVUSUPUERTOELTRIUNFU': 'Purto el Triunfo',
            'SLVUSUUSULUTAN': 'Usulutan',
            'SLVUSUSANDIONISIO': 'San Dionisio',
            'SLVUSUJUCUARAN': 'Jucuaran'
        }
    },
    SLV1357: {
        name: 'Chalatenango',
        municipalities: {
            'SLVCHANUEVACONCEPCION': 'Nueva Concepcion',
            'SLVCHAAGUACALIENTE': 'Aguacaliente',
            'SLVCHALAREINA': 'La Reina',
            'SLVCHATEJUTLA': 'Tejutla',
            'SLVCHAELPARAISO': 'El Paraiso',
            'SLVCHASANRAFAEL': 'San Rafael',
            'SLVCHASANFRANCISCOMORAZAN': 'San Francisco Morazan',
            'SLVCHASANTARITA': 'Santa Rita',
            'SLVCHACITALA': 'Itala',
            'SLVCHALAPALMA': 'La Palma',
            'SLVCHASANIGNACIO': 'San ignacion',
            'SLVCHASANFERNANDO': 'San Fernando',
            'SLVCHADULCENOMBREDEMARIA': 'Dulce Nombre de Maria',
            'SLVCHACOMALAPA': 'Comalapa',
            'SLVCHALALAGUNA': 'La Laguna',
            'SLVCHAELCARRIZAL': 'El Carrizal',
            'SLVCHAOJOSDEAGUA': 'Ojos de Agua',
            'SLVCHACONCEPCIONQUEZALTEPEQUE': 'COncepcion Quezaltepeque',
            'SLVCHALASVUELTAS': 'Las Vueltas',
            'SLVCHACHALATENANGO': 'Chalatenango',
            'SLVCHAAZACUALPA': 'Azacualpan',
            'SLVCHASANFRANCISCOLEMPA': 'San Francisco Lempa',
            'SLVCHASANANTONIOLOSRANCHOS': 'San Antonio los Ranchos',
            'SLVCHANUEVATRINIDAD': 'Nueva Trinidad',
            'SLVCHAARCATAO': 'Arcatao',
            'SLVCHANOMBREDEJESUS': 'Nombre de Jesus',
            'SLVCHALASFLORES': 'Las Flores',
            'SLVCHASANLUISDELCARMEN': 'San Luis del Carmen',
            'SLVCHASANMIGUELDEMERCEDES': 'San Miguel de Mercedes',
            'SLVCHASANANTONIODELACRUZ': 'San Antonio de la Cruz',
            'SLVCHASANISIDROLABRADOR': 'San Isidro Labrador',
            'SLVCHAPOTONICO': 'Potonico',
            'SLVCHACONCASTE': 'Concaste'
        }
    },
    SLV1358: {
        name: 'Santa Ana',
        municipalities: {
            'SLVSANSANTAANA': 'Santa Ana',
            'SLVSANELCONGO': 'El Congo',
            'SLVSANCOATEPEQUE': 'Coatepeque',
            'SLVSANSANSEBASTIANSALITRILLO': 'San Sebastian Salitrillo',
            'SLVSANELPROVENIR': 'El Porvenir',
            'SLVSANCHALCHUAPA': 'Chalchuapa',
            'SLVSANCANDELARIADELAFRONTERA': 'Candelaria de la Frontera',
            'SLVSANSANTIAGODELAFRONTERA': 'Santiago de la Frontera',
            'SLVSANSANANTONIOPAJONAL': 'San Antonio Pajonal',
            'SLVSANTEXISTEPEQUE': 'Texistepeque',
            'SLVSANMTAPAN': 'Metapan',
            'SLVSANSANTAROSAGUACHIPILIN': 'Santa Rosa Guachipilin',
            'SLVSANMASAHUAT': 'Masahuat'
        }
    }
}